USE nodelogin;

CREATE TABLE IF NOT EXISTS novedades(
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100)NOT NULL,
email VARCHAR(100)NOT NULL,
observacion VARCHAR(50)NOT NULL,
numeropaciente VARCHAR(255)NOT NULL
);
